version: "3.7"
services:
  app:
    build:
      args:
        user: fakultas-user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: ecos
    container_name: ecos-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - ecos

  reverb:
    build:
      args:
        user: fakultas-user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: ecos
    container_name: ecos-reverb
    restart: unless-stopped
    working_dir: /var/www/
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    ports:
      - "8081:8080"
    volumes:
      - ./:/var/www
    networks:
      - ecos

  queue:
    build:
      args:
        user: fakultas-user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: ecos
    container_name: ecos-queue
    restart: unless-stopped
    working_dir: /var/www/
    command: php artisan queue:work --sleep=3 --tries=3 --max-time=3600
    volumes:
      - ./:/var/www
    networks:
      - ecos

  db:
    image: mysql:5.7
    container_name: ecos-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ecos
      MYSQL_ROOT_PASSWORD: bismillah123@RGS
      MYSQL_PASSWORD: bismillah123@RGS
      MYSQL_USER: ecos
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    networks:
      - ecos

  nginx:
    image: nginx:alpine
    container_name: ecos-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - ecos

networks:
  ecos:
    driver: bridge